"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(env_file=os.path.join(BASE_DIR, ".env")) if os.path.exists(os.path.join(BASE_DIR, ".env")) else None

YOUTUBE_OAUTH_CLIENT_ID = env("YOUTUBE_OAUTH_CLIENT_ID", default=None)
YOUTUBE_OAUTH_CLIENT_SECRET = env("YOUTUBE_OAUTH_CLIENT_SECRET", default=None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="dev-key-unsafe")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = []
for h in ALLOWED_HOSTS:
    h = h.strip()
    if not h:
        continue
    if h.startswith("http://") or h.startswith("https://"):
        CSRF_TRUSTED_ORIGINS.append(h)
    else:
        # cover http/https, with and without :8000 (for dev)
        CSRF_TRUSTED_ORIGINS.append(f"http://{h}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{h}:8000")
        CSRF_TRUSTED_ORIGINS.append(f"https://{h}")
SECURE_PROXY_SSL_HEADER = ["HTTP_X_FORWARDED_PROTO", "https"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "youtubarr",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR/"youtubarr"/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        "NAME": "/data/db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# External config
LIDARR_TOKEN = env("LIDARR_TOKEN", default=None)
YOUTUBE_API_KEY = env("YOUTUBE_API_KEY", default="")
YOUTUBE_OAUTH_ACCESS_TOKEN = env("YOUTUBE_OAUTH_ACCESS_TOKEN", default="")
YOUTUBE_OAUTH_REFRESH_TOKEN = env("YOUTUBE_OAUTH_REFRESH_TOKEN", default="")
YOUTUBE_OAUTH_CLIENT_ID = env("YOUTUBE_OAUTH_CLIENT_ID", default="")
YOUTUBE_OAUTH_CLIENT_SECRET = env("YOUTUBE_OAUTH_CLIENT_SECRET", default="")
YOUTUBE_OAUTH_JSON = env("YOUTUBE_OAUTH_JSON", default="")
YOUTUBE_QUOTA_SAFE_PAGE_SIZE = int(env("YOUTUBE_QUOTA_SAFE_PAGE_SIZE", default=50))
MB_USER_AGENT = env("MB_USER_AGENT", default="YTM-Lidarr-List/0.1 (no-contact@example.com)")
MB_TIMEOUT_SECONDS = int(env("MB_TIMEOUT_SECONDS", default=45))
MB_MAX_RETRIES = int(env("MB_MAX_RETRIES", default=4))
MB_REQUEST_DELAY_SECONDS = float(env("MB_REQUEST_DELAY_SECONDS", default=1.05))
MB_ARTIST_CHUNK_SIZE = int(env("MB_ARTIST_CHUNK_SIZE", default=100))
YOUTUBE_FALLBACK_ENABLE = env.bool("YOUTUBE_FALLBACK_ENABLE", default=False)
YOUTUBE_FALLBACK_VIDEO_DIR = env("YOUTUBE_FALLBACK_VIDEO_DIR", default="/data/imports/videos")
YOUTUBE_FALLBACK_AUDIO_DIR = env("YOUTUBE_FALLBACK_AUDIO_DIR", default="/data/imports/music")
YOUTUBE_FALLBACK_MAX_PER_RUN = int(env("YOUTUBE_FALLBACK_MAX_PER_RUN", default=100))
YOUTUBE_FALLBACK_DOWNLOAD_TIMEOUT = int(env("YOUTUBE_FALLBACK_DOWNLOAD_TIMEOUT", default=900))

# Celery
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")
CELERY_TIMEZONE = "UTC"
